# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
