# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
